spring.datasource.url=jdbc:mysql://bdaluo3modgmtbwsf5yb-mysql.services.clever-cloud.com:3306/bdaluo3modgmtbwsf5yb
spring.datasource.username=uoun0qs1iclt4sfl
spring.datasource.password=yPORvsk3V8ChHhQ6lxpz
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080